[Definition]
failregex = ^<HOST>.*"(GET|POST|HEAD) /(wp-admin|wp-content|wp-includes|\.git|\.env|backup|old|new|shell|cmd|eval|xmlrpc|boaform|cgi-bin|debug|web-console|admin|setup|config).*" 444 0 "-" "-" "-"$
ignoreregex =
