import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:talker_bloc_logger/talker_bloc_logger.dart';
import 'package:talker_flutter/talker_flutter.dart';

// This file will be generated by build_runner
// Run: flutter pub run build_runner build --delete-conflicting-outputs
import 'injectable_service.config.dart';

final GetIt getIt = GetIt.instance;

@InjectableInit(preferRelativeImports: true)
Future<void> configureDependencies() async {
  await _initializeTalker();
  // This method is generated by injectable_generator
  // Run build_runner to generate it
  getIt.init();
}

Future<void> _initializeTalker() async {
  final talker = TalkerFlutter.init();
  getIt.registerSingleton<Talker>(talker);

  // Set up BLoC observer for logging BLoC events
  Bloc.observer = TalkerBlocObserver(
    talker: talker,
    settings: const TalkerBlocLoggerSettings(
      enabled: true,
      printEventFullData: true,
      printStateFullData: true,
    ),
  );
}
